const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const MESSAGE_BOX_SHOW = 'MESSAGE_BOX_SHOW';
const MESSAGE_BOX_HIDE = 'MESSAGE_BOX_HIDE';
const PROMPT_SHOW = 'PROMPT_SHOW';
const PROMPT_HIDE = 'PROMPT_HIDE';
const PROMPT_SHOW_ERROR = 'PROMPT_SHOW_ERROR';
const PROMPT_HIDE_ERROR = 'PROMPT_HIDE_ERROR';
const LOADING_BEGIN = 'LOADING_BEGIN';
const LOADING_END = 'LOADING_END';
const UPLOAD_QUESTION_ADD_NEW_QUESTION = 'UPLOAD_QUESTION_ADD_NEW_QUESTION';
const UPLOAD_QUESTION_DELETE_LAST_QUESTION = 'UPLOAD_QUESTION_DELETE_LAST_QUESTION';
const UPLOAD_QUESTION_CHANGE_PROBLEM_STATEMENT = 'UPLOAD_QUESTION_CHANGE_PROBLEM_STATEMENT';
const UPLOAD_QUESTION_CHANGE_OPTION_STATEMENT = 'UPLOAD_QUESTION_CHANGE_OPTION_STATEMENT';
const UPLOAD_QUESTION_CHANGE_ANSWER_VALUE = 'UPLOAD_QUESTION_CHANGE_ANSWER_VALUE';
const UPLOAD_QUESTION_CHANGE_CLASS_VALUE = 'UPLOAD_QUESTION_CHANGE_CLASS_VALUE';
const UPLOAD_QUESTION_CHANGE_SUBJECT_VALUE = 'UPLOAD_QUESTION_CHANGE_SUBJECT_VALUE';
const UPLOAD_QUESTION_CHANGE_CHAPTER_VALUE = 'UPLOAD_QUESTION_CHANGE_CHAPTER_VALUE';
const UPLOAD_QUESTION_RESET_ALL = 'UPLOAD_QUESTION_RESET_ALL';
const QUESTION_ACTIVE_TAB = 'QUESTION_ACTIVE_TAB';

module.exports = {
  LOADING_BEGIN,
  LOADING_END,
  USER_LOGIN,
  USER_LOGOUT,
  MESSAGE_BOX_SHOW,
  MESSAGE_BOX_HIDE,
  PROMPT_SHOW,
  PROMPT_HIDE,
  PROMPT_SHOW_ERROR,
  PROMPT_HIDE_ERROR,
  UPLOAD_QUESTION_ADD_NEW_QUESTION,
  UPLOAD_QUESTION_DELETE_LAST_QUESTION,
  UPLOAD_QUESTION_CHANGE_PROBLEM_STATEMENT,
  UPLOAD_QUESTION_CHANGE_OPTION_STATEMENT,
  UPLOAD_QUESTION_CHANGE_ANSWER_VALUE,
  UPLOAD_QUESTION_CHANGE_CLASS_VALUE,
  UPLOAD_QUESTION_CHANGE_SUBJECT_VALUE,
  UPLOAD_QUESTION_CHANGE_CHAPTER_VALUE,
  UPLOAD_QUESTION_RESET_ALL,
  QUESTION_ACTIVE_TAB
};